#version: "3.8"

services:
  postgres: #base de datos
    image: postgres:16
    container_name: morpho_key_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: morphokeydb
    ports:
      - "5432:5432"
      - "5433:5433" #segundo puerto en caso de ser necesario
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:  #pg admin como interfaz grafica
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:81"
      - "8082:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
