version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: morpho_key_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: morphokeydb
    ports:
      - "5432:5432"
      - "5433:5433" #segundo puerto en caso de ser necesario
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
